---
# defaults file for openshift-assets-install
#
# openshift_location: /tmp/openshift_install
openshift_version: 4.8.0-fc.8
openshift_mirror: "https://mirror.openshift.com"

openshift_install_command: "/usr/local/bin/openshift-install"
# dev-pre:
# {{ openshift_mirror }}/pub/openshift-v4/clients/ocp-dev-preview

# reference to OpenShift clients version
openshift_client_version: "{{ openshift_version }}"

openshift_mirror: "https://mirror.openshift.com"

openshift_location: "{{ openshift_mirror }}/pub/openshift-v4/clients/ocp/{{openshift_client_version}}"

# reference to coreos qcow file
coreos_version: "{{ openshift_version }}"
coreos_arch: x86_64
# coreos_download_url: "{{ openshift_mirror }}/pub/openshift-v4/dependencies/rhcos/{{ coreos_version.split('.')[:2]|join('.') }}/{{ coreos_version }}/rhcos-{{coreos_version}}-x86_64-qemu.x86_64.qcow2.gz"
coreos_path: /var/lib/tftpboot/coreos
coreos_download_url: "{{ openshift_mirror }}/pub/openshift-v4/dependencies/rhcos/pre-release/{{ coreos_version }}"
coreos_csum_url: "{{ openshift_mirror }}/pub/openshift-v4/dependencies/rhcos/{{ coreos_version.split('.')[:2]|join('.') }}/{{ coreos_version }}/sha256sum.txt"


# helm
helm_cli_location: "{{ openshift_mirror }}/pub/openshift-v4/clients/helm/latest/helm-linux-amd64"
